InventoryMnamgmentSystemV5/Models/AgencyUserMapping.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMnamgmentSystemV5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyUserMapping
    {
        public int RecordId { get; set; }
        public int AgencyId { get; set; }
        public int UserId { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual VUsers VUsers { get; set; }
    }
}

InventoryMnamgmentSystemV5/Controllers/AgencyUserMappingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InventoryMnamgmentSystemV5.Models;

namespace InventoryMnamgmentSystemV5.Controllers
{
    public class AgencyUserMappingsController : Controller
    {
        private InventoryManagmentSystemEntities db = new InventoryManagmentSystemEntities();

        // GET: AgencyUserMappings
        public ActionResult Index(string searchString)
        {
            var agencyUserMapping = db.AgencyUserMapping.Include(a => a.Agency).Include(a => a.VUsers);
            if (!String.IsNullOrEmpty(searchString))
            {
                agencyUserMapping = agencyUserMapping.Where(s => s.VUsers.UserName.Contains(searchString));
            }
            return View(agencyUserMapping.ToList());
        }

        // GET: AgencyUserMappings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgencyUserMapping agencyUserMapping = db.AgencyUserMapping.Find(id);
            if (agencyUserMapping == null)
            {
                return HttpNotFound();
            }
            return View(agencyUserMapping);
        }

        // GET: AgencyUserMappings/Create
        public ActionResult Create()
        {
            ViewBag.AgencyId = new SelectList(db.Agency, "AgencyID", "AgencyName");
            ViewBag.UserId = new SelectList(db.VUsers, "UserID", "UserName");
            return View();
        }

        // POST: AgencyUserMappings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RecordId,AgencyId,UserId")] AgencyUserMapping agencyUserMapping)
        {
            if (ModelState.IsValid)
            {
                db.AgencyUserMapping.Add(agencyUserMapping);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AgencyId = new SelectList(db.Agency, "AgencyID", "AgencyName", agencyUserMapping.AgencyId);
            ViewBag.UserId = new SelectList(db.VUsers, "UserID", "UserName", agencyUserMapping.UserId);
            return View(agencyUserMapping);
        }

        // GET: AgencyUserMappings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgencyUserMapping agencyUserMapping = db.AgencyUserMapping.Find(id);
            if (agencyUserMapping == null)
            {
                return HttpNotFound();
            }
            ViewBag.AgencyId = new SelectList(db.Agency, "AgencyID", "AgencyName", agencyUserMapping.AgencyId);
            ViewBag.UserId = new SelectList(db.VUsers, "UserID", "UserName", agencyUserMapping.UserId);
            return View(agencyUserMapping);
        }

        // POST: AgencyUserMappings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RecordId,AgencyId,UserId")] AgencyUserMapping agencyUserMapping)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agencyUserMapping).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AgencyId = new SelectList(db.Agency, "AgencyID", "AgencyName", agencyUserMapping.AgencyId);
            ViewBag.UserId = new SelectList(db.VUsers, "UserID", "UserName", agencyUserMapping.UserId);
            return View(agencyUserMapping);
        }

        // GET: AgencyUserMappings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgencyUserMapping agencyUserMapping = db.AgencyUserMapping.Find(id);
            if (agencyUserMapping == null)
            {
                return HttpNotFound();
            }
            return View(agencyUserMapping);
        }

        // POST: AgencyUserMappings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AgencyUserMapping agencyUserMapping = db.AgencyUserMapping.Find(id);
            db.AgencyUserMapping.Remove(agencyUserMapping);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //--------------------------------------------------------------------------------------------------------------------------------------------
        //--------------------------------------------------------------------------------------------------------------------------------------------
        public ActionResult Report()
        {
            var userAgency = db.AgencyUserMapping;

            return View(userAgency.ToList());
        }
    }
}

InventoryMnamgmentSystemV5/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryMnamgmentSystemV5.Controllers
{
    public class ReportsController : Controller
    {
        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }
    }
}

InventoryMnamgmentSystemV5/Views/AgencyUserMappings/Create.cshtml
@model InventoryMnamgmentSystemV5.Models.AgencyUserMapping

@{
    ViewBag.Title = "Create";
}

<h2>ربط مستخدم بإدارة</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>AgencyUserMapping</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="margin:7px">
            <h5>الإدارة</h5>
            <div class="">
                @Html.DropDownList("AgencyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AgencyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="margin-right:7px; margin-top:20px">
            <h5>اسم المستخدم</h5>
            <div class="">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="margin-top:7px">
                <input type="submit" value="موافق" class="btn btn-default style="border-color:#808080"" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("الصفحة الرئيسية", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InventoryMnamgmentSystemV5/Views/AgencyUserMappings/Delete.cshtml
@model InventoryMnamgmentSystemV5.Models.AgencyUserMapping

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AgencyUserMapping</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Agency.AgencyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agency.AgencyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VUsers.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VUsers.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

InventoryMnamgmentSystemV5/Views/AgencyUserMappings/Details.cshtml
@model InventoryMnamgmentSystemV5.Models.AgencyUserMapping

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AgencyUserMapping</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Agency.AgencyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agency.AgencyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VUsers.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VUsers.UserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RecordId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

InventoryMnamgmentSystemV5/Views/AgencyUserMappings/Edit.cshtml
@model InventoryMnamgmentSystemV5.Models.AgencyUserMapping

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AgencyUserMapping</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RecordId)

        <div class="form-group">
            @Html.LabelFor(model => model.AgencyId, "AgencyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AgencyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AgencyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InventoryMnamgmentSystemV5/Views/AgencyUserMappings/Index.cshtml
@model IEnumerable<InventoryMnamgmentSystemV5.Models.AgencyUserMapping>

@{
    ViewBag.Title = "Index";
}

<h2>المستخدمين حسب إداراتهم</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@

<div style="margin-top:20px; margin-right:5px">
    <form asp-controller="AgencyUserMappings" asp-action="Index">
        <p>
            اسم المستخدم: <input type="text" name="SearchString" />
            <input type="submit" value="بحث" />
        </p>
    </form>
</div>
<table class="table">
    <tr>
        <th>
            <h3>اسم المستخدم</h3>
        </th>
        <th>
            <h3>الإدارة</h3>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.VUsers.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Agency.AgencyName)
        </td>
        <td>
            @Html.ActionLink("تعديل", "Edit", new { id=item.RecordId }) |
            @Html.ActionLink("تفاصيل", "Details", new { id=item.RecordId }) |
            @Html.ActionLink("حذف", "Delete", new { id=item.RecordId })
        </td>
    </tr>
}

</table>

InventoryMnamgmentSystemV5/Views/AgencyUserMappings/Report.cshtml
@model IEnumerable<InventoryMnamgmentSystemV5.Models.AgencyUserMapping>

@{
    ViewBag.Title = "Report";
}

<h2>المستخدمين حسب الإدارة</h2>


<table class="table">
    <tr>
        <th>
           <h3>المستخدم</h3>
        </th>
        <th>
            <h3>الإدارة</h3>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.VUsers.UserName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Agency.AgencyName)
    </td>
</tr>
}

</table>