InventoryMnamgmentSystemV5/Models/IStatus.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMnamgmentSystemV5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IStatus()
        {
            this.IMovingItem = new HashSet<IMovingItem>();
            this.IReturnItem = new HashSet<IReturnItem>();
            this.UsersItems = new HashSet<UsersItems>();
            this.ItemHistory = new HashSet<ItemHistory>();
            this.Items = new HashSet<Items>();
            this.ReportingSystem = new HashSet<ReportingSystem>();
        }
    
        public int StatusID { get; set; }
        public string StatusName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMovingItem> IMovingItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IReturnItem> IReturnItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersItems> UsersItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemHistory> ItemHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportingSystem> ReportingSystem { get; set; }
    }
}

InventoryMnamgmentSystemV5/Controllers/IStatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InventoryMnamgmentSystemV5.Models;

namespace InventoryMnamgmentSystemV5.Controllers
{
    public class IStatusController : Controller
    {
        private InventoryManagmentSystemEntities db = new InventoryManagmentSystemEntities();

        // GET: IStatus
        public ActionResult Index(string searchString)
        {
            var status = from i in db.IStatus select i;

            if (!string.IsNullOrEmpty(searchString))
            {
                status = status.Where(i => i.StatusName.Contains(searchString));
            }

            return View(status.ToList());
        }

        // GET: IStatus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IStatus iStatus = db.IStatus.Find(id);
            if (iStatus == null)
            {
                return HttpNotFound();
            }
            return View(iStatus);
        }

        // GET: IStatus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: IStatus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StatusID,StatusName")] IStatus iStatus)
        {
            if (ModelState.IsValid)
            {
                db.IStatus.Add(iStatus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(iStatus);
        }

        // GET: IStatus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IStatus iStatus = db.IStatus.Find(id);
            if (iStatus == null)
            {
                return HttpNotFound();
            }
            return View(iStatus);
        }

        // POST: IStatus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StatusID,StatusName")] IStatus iStatus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(iStatus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(iStatus);
        }

        // GET: IStatus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IStatus iStatus = db.IStatus.Find(id);
            if (iStatus == null)
            {
                return HttpNotFound();
            }
            return View(iStatus);
        }

        // POST: IStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IStatus iStatus = db.IStatus.Find(id);
            db.IStatus.Remove(iStatus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InventoryMnamgmentSystemV5/Views/IStatus/Create.cshtml
@model InventoryMnamgmentSystemV5.Models.IStatus

@{
    ViewBag.Title = "Create";
}

<h2>اضافة حالة</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>IStatus</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="margin:7px">
            <h5>رمز الحالة</h5>
            <div class="">
                @Html.EditorFor(model => model.StatusID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="margin-right:7px; margin-top:20px">
            <h5>اسم الحالة</h5>
            <div class="">
                @Html.EditorFor(model => model.StatusName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StatusName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="margin-top:7px">
                <input type="submit" value="اضافة" class="btn btn-default" style="border-color:#808080"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("الصفحة الرئيسية", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InventoryMnamgmentSystemV5/Views/IStatus/Delete.cshtml
@model InventoryMnamgmentSystemV5.Models.IStatus

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>IStatus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

InventoryMnamgmentSystemV5/Views/IStatus/Details.cshtml
@model InventoryMnamgmentSystemV5.Models.IStatus

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>IStatus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StatusID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

InventoryMnamgmentSystemV5/Views/IStatus/Edit.cshtml
@model InventoryMnamgmentSystemV5.Models.IStatus

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>IStatus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StatusID)

        <div class="form-group">
            @Html.LabelFor(model => model.StatusName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StatusName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StatusName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InventoryMnamgmentSystemV5/Views/IStatus/Index.cshtml
@model IEnumerable<InventoryMnamgmentSystemV5.Models.IStatus>

@{
    ViewBag.Title = "Index";
}

<h2>حالات العناصر</h2>

<div>
    <p style="display:inline-block">
        @Html.ActionLink("اضافة حالة", "Create")
    </p>

    <form asp-controller="IStatus" asp-action="Index" style="display:inline-block; margin-right:80px">
        <p>
            اسم الحالة: <input type="text" name="searchString" />
            <input type="submit" value="بحث" />
        </p>
    </form>
</div>

<table class="table">
    <tr>
        <th>
            <h3>الحالة</h3>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StatusName)
        </td>
        <td>
            @Html.ActionLink("تعديل", "Edit", new { id=item.StatusID }) |
            @Html.ActionLink("تفاصيل", "Details", new { id=item.StatusID }) |
            @Html.ActionLink("حذف", "Delete", new { id=item.StatusID })
        </td>
    </tr>
}

</table>